query GetNavigation($identifier: String!, $locale: Locale!) {
  navigations(
    where: { identifier: $identifier }
    locales: [$locale, en]
    stage: DRAFT
    first: 1
  ) {
    id
    identifier
    items {
      id
      label
      pageLink {
        id
        slug
      }
    }
  }
}
