query GetProducts($locale: Locale!) {
  products(locales: [$locale, en], stage: DRAFT, first: 20) {
    id
    slug
    name
    tagline
    bikeCategory
    category {
      value
    }
    imageUrl
    productFeatures
    featured
    specifications {
      frame
      weight
      groupset
      wheels
    }
    externalProductId
    externalProduct {
      data {
        calculated_price
        sale_price
        inventory_level
        availability
      }
    }
  }
}

query GetFeaturedProducts($locale: Locale!) {
  products(
    locales: [$locale, en]
    stage: DRAFT
    first: 4
    where: { featured: true }
  ) {
    id
    slug
    name
    tagline
    bikeCategory
    category {
      value
    }
    imageUrl
    productFeatures
    specifications {
      frame
      weight
      groupset
      wheels
    }
    externalProduct {
      data {
        calculated_price
        sale_price
        inventory_level
        availability
      }
    }
  }
}

query GetProductCategories {
  products(stage: DRAFT, first: 100) {
    category {
      value
    }
  }
}
