query GetProductBySlug($slug: String!, $locale: Locale!) {
  product(where: { slug: $slug }, locales: [$locale, en], stage: DRAFT) {
    id
    slug
    name
    tagline
    bikeCategory
    description {
      text
    }
    category {
      value
    }
    imageUrl
    productFeatures
    featured
    specifications {
      frame
      motor
      battery
      range
      weight
      groupset
      gears
      brakes
      suspension
      wheelSize
      wheels
    }
    externalProductId
    externalProduct {
      data {
        calculated_price
        sale_price
        inventory_level
        availability
      }
    }
  }
}
