query GetProductBySlug($slug: String!, $locale: Locale!) {
  product(where: { slug: $slug }, locales: [$locale, en], stage: DRAFT) {
    id
    slug
    name
    tagline
    description {
      text
    }
    category {
      value
    }
    image {
      url
      width
      height
    }
    productFeatures
    featured
    specifications {
      frame
      motor
      battery
      range
      weight
      groupset
      gears
      brakes
      suspension
      wheelSize
      wheels
    }
    externalProductId
    externalProduct {
      data {
        calculated_price
        sale_price
        inventory_level
        availability
        variants {
          calculated_price
          option_values {
            id
            label
            option_id
            option_display_name
          }
        }
      }
    }
  }
}
