query GetSiteSettings($locale: Locale!) {
  allSiteSettings(locales: [$locale, en], stage: DRAFT, first: 1) {
    id
    siteName
    brandColor
    contactEmail
    announcement {
      html
    }
    footerText {
      text
    }
    footerSubscribeTitle
    footerSubscribeSubtitle
    socialLinks {
      id
      platform
      url
      handle
    }
    mainNavigation {
      id
      items {
        id
        label
        pageLink {
          id
          slug
        }
      }
    }
    footerNavigation {
      id
      items {
        id
        label
        pageLink {
          id
          slug
        }
      }
    }
  }
}
