query GetSiteSettings($locale: Locale!) {
  allSiteSettings(locales: [$locale, en], stage: DRAFT, first: 1) {
    id
    siteName
    brandColor
    contactEmail
    footerText {
      text
    }
    logo {
      id
      url
      width
      height
    }
    socialLinks {
      id
      platform
      url
      handle
    }
    mainNavigation {
      id
      items {
        id
        label
        linkType
        externalUrl
        pageLink {
          id
          slug
        }
      }
    }
    footerNavigation {
      id
      items {
        id
        label
        linkType
        externalUrl
        pageLink {
          id
          slug
        }
      }
    }
  }
}
